exclude: '.git|.tox|.trash'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint

  -   repo: https://github.com/klieret/jekyll-relative-url-check
      rev: v2.0.1
      hooks:
      -   id: jekyll-relative-url-check-html
      -   id: jekyll-relative-url-check-markdown
